services:
  api:
    build:
      context: .
      dockerfile: src/TestJob.Api/Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./src:/app/src
      - /app/src/TestJob.Api/bin
      - /app/src/TestJob.Api/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=testjob;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testjob
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testjob"]
      interval: 3s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    entrypoint:
      - /bin/sh
      - -c
      - "/venv/bin/python3 /pgadmin4/setup.py load-servers /pgadmin4/servers.json && /entrypoint.sh"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: